services:
  postgres:
    image: postgres:16-alpine
    container_name: gamerboxd-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gamerboxd
      POSTGRES_PASSWORD: gamerboxd123
      POSTGRES_DB: gamerboxd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
